python -m sample.generate --model_path ./save/full/2025/ckpt/model000090000.pt --datapath 'dataset/wild_data/cello/juke_feature' --filename '{"audio":"your_audio.npy"}'

### only for quantitative evaluation
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello01.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello08.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello05.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello12.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello26_1.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello26_2.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello26_3.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello45.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello47.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello59_1.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello59_2.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_1.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_2.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_3.npy"}'
# python -m sample.generate --model_path ./save/hicl_0_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_4.npy"}'

# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello01.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello08.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello05.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello12.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello26_1.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello26_2.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello26_3.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello45.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello47.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello59_1.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello59_2.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_1.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_2.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_3.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_0_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_4.npy"}'

# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello01.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello08.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello05.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello12.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello26_1.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello26_2.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello26_3.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello45.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello47.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello59_1.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello59_2.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_1.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_2.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_3.npy"}'
# python -m sample.generate --model_path ./save/hicl_1_bicl_1_partial/your_timestamp/ckpt/model000090000.pt --datapath 'dataset/SPD-GEN/cello/test_data/juke_feature' --filename '{"audio":"cello60_4.npy"}'